version: '2'
services:
  mosque-db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    image: mosque/db
    container_name: mosque-db
    restart: always
    networks:
      - default
    volumes:
      - data-db:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=Europe/Berlin

  mosque-api:
    build:
      context: ./app
    image: mosque/api
    container_name: mosque-api
    restart: always
    depends_on: 
      - mosque-db
    networks:
      - default
    volumes:
      - data-img:/app/img
      - ./app:/app
    ports:
      - "${API_PORT}:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - TZ=Europe/Berlin
      - APP_ID=${APP_ID}
      - APP_SIGNATURE=${APP_SIGNATURE}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://${DB_USER}:${DB_PASS}@mosque-db:3306/${DB_NAME}?charset=latin1

networks:
  default:
    driver: bridge

volumes:
  data-db:
    external: false
    driver: local
  data-img:
    external: false
    driver: local